@startuml
loop for hver spiller
    Spiller -> Stigespill
    Stigespill -> Terning : Trill()
    Terning -> Stigespill
    Stigespill -> Spiller
    Spiller -> Stigespill : endrePos()
    Stigespill -> Brett : endrePos()

    alt Havner på stige/slange
        Brett -> Brett
    end
    Brett -> Stigespill
    Stigespill -> Spiller
    == Hvis 6'er fra trill(), utfør trill() igjen ==
end

@enduml