@startuml
:User: -right-> (Trill Terning)
(Trill Terning) -right-> :User med terning:
:User med terning: -down-> (Flytter brikke)
(Flytter brikke) -> (rute)
(rute) -> (Flytter brikke)
(Flytter brikke) -> User
@enduml